-- Create a table for public profiles
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  mobile TEXT,
  user_type INTEGER DEFAULT 0, -- 0 = Student, 1 = Teacher
  student_id TEXT,
  degree TEXT,
  department TEXT,
  university TEXT,
  profile_picture TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Create policies for profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Courses Table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  course_code TEXT UNIQUE NOT NULL,
  subject TEXT,
  semester TEXT,
  batch TEXT,
  description TEXT,
  department TEXT,
  banner_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  self_join_enabled BOOLEAN DEFAULT TRUE,
  access_key TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  teacher_id UUID REFERENCES profiles(id) NOT NULL
);

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Courses are viewable by everyone" ON courses;
CREATE POLICY "Courses are viewable by everyone" ON courses FOR SELECT USING (true);

DROP POLICY IF EXISTS "Teachers can manage their own courses" ON courses;
CREATE POLICY "Teachers can manage their own courses" ON courses FOR ALL USING (auth.uid() = teacher_id);

-- Enrollments Table
CREATE TABLE IF NOT EXISTS enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  enrolled_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, course_id)
);

ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enrollments viewable by student and teacher" ON enrollments;
CREATE POLICY "Enrollments viewable by student and teacher" ON enrollments FOR SELECT USING (
  auth.uid() = student_id OR 
  EXISTS (SELECT 1 FROM courses WHERE id = course_id AND teacher_id = auth.uid())
);

DROP POLICY IF EXISTS "Students can enroll themselves" ON enrollments;
CREATE POLICY "Students can enroll themselves" ON enrollments FOR INSERT WITH CHECK (auth.uid() = student_id);

-- Quizzes Table
CREATE TABLE IF NOT EXISTS quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  duration INTEGER, -- in minutes
  deadline TIMESTAMPTZ,
  passing_marks INTEGER,
  total_marks INTEGER,
  access_key TEXT,
  attempts_count INTEGER DEFAULT 1,
  max_questions INTEGER DEFAULT 0,
  shuffle_questions BOOLEAN DEFAULT FALSE,
  eye_tracking_enabled BOOLEAN DEFAULT FALSE,
  fullscreen_required BOOLEAN DEFAULT FALSE,
  tab_switch_detection BOOLEAN DEFAULT FALSE,
  violation_limit INTEGER DEFAULT 5,
  status TEXT DEFAULT 'draft', -- draft, scheduled, live, ended
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Quizzes viewable by enrolled students and teachers" ON quizzes;
CREATE POLICY "Quizzes viewable by enrolled students and teachers" ON quizzes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Teachers can manage quizzes in their courses" ON quizzes;
CREATE POLICY "Teachers can manage quizzes in their courses" ON quizzes FOR ALL USING (
  EXISTS (SELECT 1 FROM courses WHERE id = course_id AND teacher_id = auth.uid())
);

-- Questions Table
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES quizzes ON DELETE CASCADE NOT NULL,
  text TEXT NOT NULL,
  option_a TEXT,
  option_b TEXT,
  option_c TEXT,
  option_d TEXT,
  correct_option TEXT, -- 'a', 'b', 'c', or 'd'
  point_value INTEGER DEFAULT 1,
  question_type TEXT DEFAULT 'mcq',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Questions viewable by those with quiz access" ON questions;
CREATE POLICY "Questions viewable by those with quiz access" ON questions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Teachers can manage questions for their quizzes" ON questions;
CREATE POLICY "Teachers can manage questions for their quizzes" ON questions FOR ALL USING (
  EXISTS (SELECT 1 FROM quizzes q JOIN courses c ON q.course_id = c.id WHERE q.id = quiz_id AND c.teacher_id = auth.uid())
);

-- Results Table
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) NOT NULL,
  quiz_id BIGINT REFERENCES quizzes ON DELETE CASCADE NOT NULL,
  score INTEGER,
  total_marks INTEGER,
  eye_tracking_violations INTEGER DEFAULT 0,
  timeline JSONB,
  answers JSONB,
  feedback JSONB,
  graded_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Students can view their own results" ON results;
CREATE POLICY "Students can view their own results" ON results FOR SELECT USING (auth.uid() = student_id);

DROP POLICY IF EXISTS "Teachers can view results for their quizzes" ON results;
CREATE POLICY "Teachers can view results for their quizzes" ON results FOR SELECT USING (
  EXISTS (SELECT 1 FROM quizzes q JOIN courses c ON q.course_id = c.id WHERE q.id = quiz_id AND c.teacher_id = auth.uid())
);

DROP POLICY IF EXISTS "Students can insert their own results" ON results;
CREATE POLICY "Students can insert their own results" ON results FOR INSERT WITH CHECK (auth.uid() = student_id);

-- Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  title TEXT,
  message TEXT,
  type TEXT, -- 'course', 'quiz', 'system'
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own notifications" ON notifications;
CREATE POLICY "Users can view their own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications" ON notifications FOR UPDATE USING (auth.uid() = user_id);

-- Leave Requests Table
CREATE TABLE IF NOT EXISTS leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) NOT NULL,
  course_id BIGINT REFERENCES courses ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'pending', -- pending, accepted, declined
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users involved can view leave requests" ON leave_requests;
CREATE POLICY "Users involved can view leave requests" ON leave_requests FOR SELECT USING (
  auth.uid() = student_id OR 
  EXISTS (SELECT 1 FROM courses WHERE id = course_id AND teacher_id = auth.uid())
);

DROP POLICY IF EXISTS "Students can create leave requests" ON leave_requests;
CREATE POLICY "Students can create leave requests" ON leave_requests FOR INSERT WITH CHECK (auth.uid() = student_id);

DROP POLICY IF EXISTS "Teachers can update leave requests for their courses" ON leave_requests;
CREATE POLICY "Teachers can update leave requests for their courses" ON leave_requests FOR UPDATE USING (
  EXISTS (SELECT 1 FROM courses WHERE id = course_id AND teacher_id = auth.uid())
);

-- Function to handle new user profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, user_type)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email, (new.raw_user_meta_data->>'user_type')::integer);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create profile on signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =======================================================
-- PATCHES FOR EXISTING DATABASES
-- These ensure that if tables were created previously,
-- they are updated with the correct columns and foreign keys.
-- =======================================================

-- 1. Add missing columns
ALTER TABLE courses ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE results ADD COLUMN IF NOT EXISTS graded_at TIMESTAMPTZ;

-- 2. Update Foreign Keys to point to 'profiles' instead of 'auth.users'
ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_teacher_id_fkey;
ALTER TABLE courses ADD CONSTRAINT courses_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id);

ALTER TABLE enrollments DROP CONSTRAINT IF EXISTS enrollments_student_id_fkey;
ALTER TABLE enrollments ADD CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id);

ALTER TABLE results DROP CONSTRAINT IF EXISTS results_student_id_fkey;
ALTER TABLE results ADD CONSTRAINT results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id);

ALTER TABLE leave_requests DROP CONSTRAINT IF EXISTS leave_requests_student_id_fkey;
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id);

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- 3. Ensure all existing users have a profile
INSERT INTO public.profiles (id, full_name, email)
SELECT id, raw_user_meta_data->>'full_name', email
FROM auth.users
WHERE id NOT IN (SELECT id FROM public.profiles);
